### ISSUE TITLE
Frequently create binary releases of the installer

### ISSUE THREAD

**Issue by kuruczgy** [kuruczgy/x1e-nixos-config#18]
I just need to figure out how to conveniently create releases on GitHub. While if you are very paranoid you might still want to build everything from source, many people would probably prefer to skip the hours of compile time (especially if just doing some quick testing for the first time with their new laptop).

Automated builds are probably out of the question for now, but for the foreseeable future manual uploads by me should work well enough.

**Comment by korken89** [comment]
A note on the build, it only takes ~20 min on the 7x if you do it in WSL. It makes the compile a lot less of a burden :)

**Comment by kuruczgy** [comment]
Hm... using WSL is quite clever actually, given that this is my first serious aarch64 machine I only saw cross compiling from x86 as the straightforward path to bootstrapping. (And for cross compiled packages you don't have a binary cache, so you have to compile _everything_ from scratch.)

**Comment by alyraffauf** [comment]
Is there a WSL aarch64 build of NixOS? I mean you can just use Ubuntu and install Nix yourself, but I wasn't sure if the NixOS 'app' was native or not.

**Comment by kuruczgy** [comment]
Note: If either of you document the procedure for compiling using WSL, a PR to adding it as an additional section to the README is welcome :)

(I don't think I ever managed to use WSL successfully for anything so I am a noob at this.)

**Comment by kuruczgy** [comment]
Just created a release, it was relatively simple. I don't see why I couldn't create one after every update to `main`.

I would prefer to document the procedure, so I will wait until I do so before closing this issue.

**Comment by korken89** [comment]
What I did is that I started a WSL NixOS (followed the README of https://github.com/nix-community/NixOS-WSL to add it), Ubuntu is probably just as fine with Nix shell, updated flake.nix to use `aarch64-linux` as build system, and ran the nix command with the addition of `--extra-experimental-features 'nix-command flakes'`.

I can write an addition to the README on this, no problem.  🚀

**Comment by korken89** [comment]
Just to try I did the same on Debian with Nix shell, and it works just as well. ~24 min build time.
