### ISSUE TITLE
No wifi after the install 

### ISSUE THREAD

**Issue by celproject** [kuruczgy/x1e-nixos-config#19]
Hi, tnx for this easy install.

But after I installed it, and reinstalled it to make sure I didn't mess up something.
I cant get the W1P4p1s0 adapter to go up and thus no wpa supplicant. ( was ok on the iso ) 

Any ideas what I can be doing wrong? I am not very familiar with Nix

Thank you

**Comment by kuruczgy** [comment]
Hi! The installed system is configured to use NetworkManager, you should be able to use `nmtui` to connect to Wi-Fi.

**Comment by celproject** [comment]
Omg, that wes easy thank you very much!
