### ISSUE TITLE
Add a proper feature matrix to the README

### ISSUE THREAD

**Issue by kuruczgy** [kuruczgy/x1e-nixos-config#21]
_Originally posted by @alyraffauf in https://github.com/kuruczgy/x1e-nixos-config/discussions/20#discussioncomment-10825832_

Is it possible to come up with a feature matrix not unlike the ones that asahi has? Their SoC support matrix is a little too detailed, but we could devise a practical one (wifi, bluetooth, suspend, speakers, etc).
![image](https://github.com/user-attachments/assets/8ccd5794-553f-4458-a9cf-5217b9bbf917)
![image](https://github.com/user-attachments/assets/57af0cd6-907b-4a6a-bba8-c5fdb47656c0)

**Comment by kuruczgy** [comment]
Tbh I don't wouldn't mind it being too detailed, surely better than not being detailed enough. (Which the README evidently is right now.)

I guess we could have something like 3 categories for support. (working, not working, or half working (with an asterisk and a more detailed description below))

**Comment by alyraffauf** [comment]
> Tbh I don't wouldn't mind it being too detailed, surely better than not being detailed enough. (Which the README evidently is right now.)
> 
> I guess we could have something like 3 categories for support. (working, not working, or half working (with an asterisk and a more detailed description below))

something like this might be a good starting point:
| Feature           | Status | Notes                       |
|-------------------|-------:|-----------------------------|
| Display           |      ✓ |                             |
| Keyboard          |      ✓ |                             |
| Touchpad          |      ✓ |                             |
| USB-C             |      ✓ |                             |
| USB-C DP Alt Mode |      ? |                             |
| Camera            |      ? |                             |
| Suspend           |      ✓ | Lid switch not yet working. |
| Hibernate         |      ? |                             |
| Microphone        |      ? |                             |
| Speakers          |      x |                             |
| Power Management  |      ? |                             |
| WiFi              |      ✓ |                             |

We can include things like minimum kernel version or specific patches in the notes as well.
