### ISSUE TITLE
Add touchscreen and RTC to feature matrix

### ISSUE THREAD

**Issue by kuruczgy** [kuruczgy/x1e-nixos-config#30]
Touchscreen working perfectly, RTC not :/

**Comment by kuruczgy** [comment]
Also maybe something about thermal management. It seems at least somewhat broken? I sometimes get a thermal panic when kernel compiling, so it's clear that the kernel is not consistent with thermal throttling. (Maybe it's just not doing any throttling at all?)

**Comment by JakoDel** [comment]
> Also maybe something about thermal management. It seems at least somewhat broken? I sometimes get a thermal panic when kernel compiling, so it's clear that the kernel is not consistent with thermal throttling. (Maybe it's just not doing any throttling at all?)

https://lore.kernel.org/lkml/20241030130840.2890904-1-quic_sibis@quicinc.com/

looks like it isnt

**Comment by kuruczgy** [comment]
> https://lore.kernel.org/lkml/20241030130840.2890904-1-quic_sibis@quicinc.com/
> 
> looks like it isnt, or at least, not properly.

Hm but something is still wrong though, these patches are included in the 6.12-rc5 branch used in this repo, but I still got a thermal panic just yesterday using this kernel.

**Comment by korken89** [comment]
Weird, I'm not getting thermal panics 🤔 I can try to make mine panic while building the kernel.

**Comment by kuruczgy** [comment]
Required conditions for overheating for me:
- Kernel compile (a full one, at least ~10 minutes in)
- Laptop on a flat surface. I got the advice on matrix to elevate the back of the laptop a little to get better airflow, and that indeed does seem to avoid the overheating.

On overheating the laptop simply shuts down. I can see the following messages afterwards using `journalctl -b -1`:

```
Nov 09 23:34:20 cobalt kernel: thermal thermal_zone26: cpu2-0-btm-thermal: critical temperature reached
Nov 09 23:34:20 cobalt kernel: reboot: HARDWARE PROTECTION shutdown (Temperature too high)
Nov 09 23:34:20 cobalt systemd-logind[1401]: The system will power off now!
Nov 09 23:34:20 cobalt systemd-logind[1401]: System is powering down.
```
