### ISSUE TITLE
Update to 6.12-rc7

### ISSUE THREAD

**Issue by kuruczgy** [kuruczgy/x1e-nixos-config#36]
https://github.com/jhovold/linux/tree/wip/x1e80100-6.12-rc6

**Comment by powpingdone** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/qcom/x1e80100?id=feb324e3118ac04f579888e9019e60e62fed27c8 Heads up, the linux-firmware repo was updated with *some* of the .jsn files used.

**Comment by powpingdone** [comment]
https://github.com/jhovold/linux/tree/wip/x1e80100-6.12-rc7 has hit
