### ISSUE TITLE
Rebuilding from flake returns 404 error for some patch file

### ISSUE THREAD

**Issue by eureka-cpu** [kuruczgy/x1e-nixos-config#54]
Hello, I just tried adding a few packages to the flake after following the instructions to use a custom config from the readme and got this error:

```
sudo nixos-rebuild switch --flake .#system
building the system configuration...
evaluation warning: system.stateVersion is not set, defaulting to 25.05. Read why this matters on https://nixos.org/manual/nixos/stable/options.html#opt-system.stateVersion.
error: builder for '/nix/store/hffr0zj27bfsfl0m9ingzkqhqxnsb6r7-9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch.drv' failed with exit code 1;
       last 7 log lines:
       >
       > trying https://github.com/hogliux/linux-yoga-7x/commit/9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
       > curl: (22) The requested URL returned error: 404
       > error: cannot download 9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch from any mirror
       For full logs, run 'nix log /nix/store/hffr0zj27bfsfl0m9ingzkqhqxnsb6r7-9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch.drv'.
error: 1 dependencies of derivation '/nix/store/m91jyza4z1afcfdsbd0id5qdjzbi79ji-linux-6.12.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/6k74sg5larjswhd5qrrbwngasvm3imi0-nixos-system-system-25.05.20241128.bfe7bb4.drv' failed to build
```

**Comment by eureka-cpu** [comment]
Looks like that repository no longer exists?

**Comment by eureka-cpu** [comment]
Opening a PR, looks like there is some other place those patches are being hosted now. Feel free to edit the PR if I'm barking up the wrong tree.

**Comment by eureka-cpu** [comment]
@hogliux was this patched removed due to the changes being merged into the yoga7x-firmware repo?

**Comment by kuruczgy** [comment]
Actually I think he mentioned that he was using my kernel, so he might have deleted his repo as he no longer needed it. Talk about circular dependencies :laughing: 

Here is the patch from my nix store:

```diff
--- a/arch/arm64/boot/dts/qcom/x1e80100-lenovo-yoga-slim7x.dts
+++ b/arch/arm64/boot/dts/qcom/x1e80100-lenovo-yoga-slim7x.dts
@@ -15,6 +15,11 @@
 	model = "Lenovo Yoga Slim 7x";
 	compatible = "lenovo,yoga-slim7x", "qcom,x1e80100";
 
+	aliases {
+		serial0 = &uart21;
+		serial1 = &uart14;
+	};
+
 	pmic-glink {
 		compatible = "qcom,x1e80100-pmic-glink",
 			     "qcom,sm8550-pmic-glink",
@@ -794,6 +799,14 @@
 			       <44 4>, /* SPI (TPM) */
 			       <238 1>; /* UFS Reset */
 
+        bt_en_default: bt-en-sleep {
+		pins = "gpio116";
+		function = "gpio";
+		output-low;
+		bias-disable;
+		qcom,drive-strength = <16>;
+	};
+
 	edp_reg_en: edp-reg-en-state {
 		pins = "gpio70";
 		function = "gpio";
@@ -883,6 +896,18 @@
 
 };
 
+&uart14 {
+	status = "okay";
+
+	bluetooth: bt_wcn7850 {
+		compatible = "qcom,wcn7850-bt";
+		pinctrl-names = "default";
+		pinctrl-0 = <&bt_en_default>;
+		enable-gpios = <&tlmm 116 GPIO_ACTIVE_HIGH>;
+		max-speed = <3200000>;
+	};
+};
+
 &usb_1_ss0_hsphy {
 	vdd-supply = <&vreg_l3j_0p8>;
 	vdda12-supply = <&vreg_l2j_1p2>;
```

This hashes to `sha256-2ZfDkbhriRb+52WNc6wlUKZPp55zKCJgxmkf/3m+m2M=`, so should be a perfect replacement for the original one.

We should put this file in this repo. Since @eureka-cpu you said you are good with nix, what's the easiest way to create a FOD from a file in the repo? (If we do that I think we can avoid rebuilds.)

**Comment by kuruczgy** [comment]
Nope, unfortunately that produces an output path like `/nix/store/n9z8w05ssl3pzyzqa0ckviqbrlisldvx-source`, which does not match the original `/nix/store/dycn9fnf4bsj9n3cqimrjzzakhdwi4n5-9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch`.

I think I came up with a solution, though it's definitely a bit contrived. Can you test #55 and see if it works for you?

**Comment by eureka-cpu** [comment]
Sure, happy to !

**Comment by eureka-cpu** [comment]
Also, maybe using one of the trivial writers would be better here? They call runCommand under the hood like you are here.
https://noogle.dev/f/pkgs/writeTextFile

**Comment by kuruczgy** [comment]
Over in the Lix matrix some smart people cooked this up:
```nix
      fetchpatch {
        name = "9829ac9dd0e827cc62242d8ae8b534e31ffd00bd.patch";
        url = "file://${./packages/lenovo-yoga-slim7x-bluetooth.patch}";
        hash = "sha256-2ZfDkbhriRb+52WNc6wlUKZPp55zKCJgxmkf/3m+m2M=";
      };
```

**Comment by eureka-cpu** [comment]
I almost recommended you this, but semantically it didn't feel right 😅 j

**Comment by kuruczgy** [comment]
It's a disgusting hack, but tbh I will go with this unless you object, I like it since it so closely matches the original.

**Comment by eureka-cpu** [comment]
Hey it's all good, this is your repo! My only argument against it is that fetchers generally imply a network call, and if you don't need that then it makes more semantic sense to write a file to the store instead, or do as you already have 🙂

**Comment by hogliux** [comment]
> @hogliux was this patched removed due to the changes being merged into the yoga7x-firmware repo?

Ooopss. I changed the repo to a private repo as I'm including some non-public changes to my repo. I didn't think that anybody was relying on my repo for anything. Sorry about that. Looks like it's fixed now. Should I make my repo public again?

**Comment by kuruczgy** [comment]
@hogliux Yeah it's all good, we already fixed it. I think the only external dep for kernel patches now is lore.kernel.org, hopefully that's reliable enough.
