### ISSUE TITLE
Reformat project using `nixfmt-rfc-style`

### ISSUE THREAD

**Issue by kuruczgy** [kuruczgy/x1e-nixos-config#56]

**Comment by eureka-cpu** [comment]
afaik the rfc style formatter is still pretty rough around the edges, personally I still use the nixpkgs-fmt but I also see alejandra quite a bit too

**Comment by kuruczgy** [comment]
Nixpkgs is already enforcing its usage for some files: https://github.com/NixOS/nixpkgs/pull/326407

Here is the formatter tracking issue, it seems that they are planning on reformatting the whole nixpkgs repo in the near future: https://github.com/NixOS/nixfmt/issues/153
