### ISSUE TITLE
Consider not using lib.mkForce in boot.initrd.availableKernelModules

### ISSUE THREAD

**Issue by msackman** [kuruczgy/x1e-nixos-config#66]
Using `mkForce` in modules/x1e80100.nix is problematic because it nukes out other modules. I've just spent a long and "educational" evening setting up my laptop with cryptSetup and LUKS, and getting very frustrated that modules needed for LUKS and crypto seemingly weren't making it through to the initrd/initramfs etc.

You can drop the use of `mkForce` if you use `boot.initrd.includeDefaultModules = false`.
If you're also using `boot.initrd.systemd.enable = true` then you need to disable `tpm2`.

*If* I edit your modules/x1e80100.nix and drop the `mkForce` then the below works for me. It's quite likely I can trim down the `availableKernelModules` some more, but this does work - gets the LUKS root unlocked in stage1 init, and then all the other FSs are under that LVM volume.

```
  boot.initrd = {
    includeDefaultModules = false;
    availableKernelModules = [ "nvme" "nvme_core" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" "dm_crypt" "encrypted_keys" "trusted" "asn1_encoder" "tee" "tpm" ];
    kernelModules = [ ];
    luks.devices.root = {
      device = "/dev/disk/by-partuuid/6cf777dc-5188-4cf3-aa0b-91210598c6e1";
      preLVM = true;
      allowDiscards = true;
    };
    systemd = {
      enable = true;
      tpm2.enable = false;
    };
  };
```

**Comment by kuruczgy** [comment]
Ah good point, did not know `boot.initrd.includeDefaultModules` existed, seems like a perfectly valid solution instead of `mkForce`. Feel free to make a PR (I can also make one in a couple days when I have time).

**Comment by kuruczgy** [comment]
And sorry about this, when I was originally setting this up I obviously used `mkForce` as a quick & dirty solution, and then I guess later I forgot to look for a proper solution instead...

**Comment by kuruczgy** [comment]
If I do

```diff
diff --git a/modules/x1e80100.nix b/modules/x1e80100.nix
index 530e73c..da4eab1 100644
--- a/modules/x1e80100.nix
+++ b/modules/x1e80100.nix
@@ -1,13 +1,8 @@
 { pkgs, lib, ... }:
 
 {
-  boot.initrd.availableKernelModules = lib.mkForce [
-    # Needed by the NixOS iso for booting in general
-    "squashfs"
-    "iso9660"
-    "uas"
-    "overlay"
-
+  boot.initrd.includeDefaultModules = false;
+  boot.initrd.availableKernelModules = [
     # Definitely needed for USB:
     "usb_storage"
     "phy_qcom_qmp_combo"
```

it seems that the ISO still includes a bunch of unnecessary stuff:
`nix eval .#nixosConfigurations.iso.config.boot.initrd.availableKernelModules`:
```
[ "ahci" "ata_piix" "sata_inic162x" "sata_nv" "sata_promise" "sata_qstor" "sata_sil" "sata_sil24" "sata_sis" "sata_svw" "sata_sx4" "sata_uli" "sata_via" "sata_vsc" "pata_ali" "pata_amd" "pata_artop" "pata_atiixp" "pata_efar" "pata_hpt366" "pata_hpt37x" "pata_hpt3x2n" "pata_hpt3x3" "pata_it8213" "pata_it821x" "pata_jmicron" "pata_marvell" "pata_mpiix" "pata_netcell" "pata_ns87410" "pata_oldpiix" "pata_pcmcia" "pata_pdc2027x" "pata_qdi" "pata_rz1000" "pata_serverworks" "pata_sil680" "pata_sis" "pata_sl82c105" "pata_triflex" "pata_via" "pata_winbond" "3w-9xxx" "3w-xxxx" "aic79xx" "aic7xxx" "arcmsr" "hpsa" "uas" "sdhci_pci" "nvme" "ohci1394" "sbp2" "virtio_net" "virtio_pci" "virtio_mmio" "virtio_blk" "virtio_scsi" "virtio_balloon" "virtio_console" "mptspi" "vmxnet3" "vsock" "sun4i-drm" "sun8i-mixer" "pwm-sun4i" "vc4" "pcie-brcmstb" "dw-hdmi" "dw-mipi-dsi" "rockchipdrm" "rockchip-rga" "phy-rockchip-pcie" "pcie-rockchip-host" "panel-simple" "pwm-bl" "axp20x-ac-power" "axp20x-battery" "pinctrl-axp209" "mp8859" "xhci-pci-renesas" "reset-raspberrypi" "analogix-dp" "analogix-anx6345" "squashfs" "iso9660" "uas" "overlay" "usb_storage" "phy_qcom_qmp_combo" "phy_qcom_snps_eusb2" "phy_qcom_eusb2_repeater" "tcsrcc_x1e80100" "i2c_hid_of" "i2c_qcom_geni" "dispcc-x1e80100" "gpucc-x1e80100" "phy_qcom_edp" "panel_edp" "msm" "nvme" "phy_qcom_qmp_pcie" "pcie_qcom" "panel_samsung_atna33xc20" "ps883x" "pmic_glink_altmode" "qrtr" "md_mod" "raid0" "raid1" "raid10" "raid456" "squashfs" "ext2" "ext4" ]
```

**Comment by msackman** [comment]
> And sorry about this, when I was originally setting this up I obviously used mkForce as a quick & dirty solution, and then I guess later I forgot to look for a proper solution instead...

Please don't worry - without your work on this I probably wouldn't have even bought this laptop.

**Comment by msackman** [comment]
> I am talking about the installer ISO, not the installed system
Yeah I did spot that and wonder whether that was the difference.
